name: BlackjackInvMenu
main: FixStudios\Blackjack\BlackjackPlugin
version: 1.0.0
api: 5.0.0
author: FixStudios
description: A blackjack plugin using InvMenu and BedrockEconomy

permissions:
  blackjack.cmd:
    description: Allows the player to use the /bj command
    default: true

commands:
  bj:
    description: Start a blackjack game
    usage: "/bj [amount]"
    permission: blackjack.cmd

depend:
  - BedrockEconomy
  - InvMenu
